/**
 * Centralized Branding Configuration for IDS Pulse
 * Integrity Driven Solutions Inc. (IDS)
 */

import { LOGO_BASE64, LOGO_BASE64_DARK_TEXT, LOGO_BASE64_WHITE_TEXT } from '../components/LogoBase64.js';

export const BRANDING_CONFIG = {
  organizationName: 'Integrity Driven Solutions Inc.',
  organizationShort: 'IDS',
  productName: 'Automotive Pulse',
  version: 'v3.0.0',
  taxRegistrationNumber: '853120236 RT0001',
  logo: {
    canonical: LOGO_BASE64,
    darkText: LOGO_BASE64_DARK_TEXT,
    whiteText: LOGO_BASE64_WHITE_TEXT,
    aspectRatio: 250 / 60, // 4.167
    defaultHeaderWidthMm: 46,
    defaultHeaderHeightMm: 11
  },
  colors: {
    primary: '#031D37',
    primaryRgb: [3, 29, 55],
    secondary: '#0969DC',
    secondaryRgb: [9, 105, 220],
    textPrimary: '#0F172A',
    textRgb: [15, 23, 42],
    textSecondary: '#64748B',
    textSecondaryRgb: [100, 116, 139],
    backgroundLight: '#F8FAFC',
    backgroundRgb: [248, 250, 252],
    borderSubtle: '#E2E8F0',
    borderRgb: [226, 232, 240]
  },
  typography: {
    minBodySizePt: 10,
    minTableDataSizePt: 9,
    minTableHeaderSizePt: 9.5,
    minHeadingSizePt: 12
  },
  footer: {
    confidentialNotice: 'Automotive Pulse — Confidential Executive Report',
    systemAuditNotice: 'Generated by Automotive Pulse Platform | Integrity Driven Solutions Inc. (IDS)'
  },
  reportDefaults: {
    confidentialNotice: 'Automotive Pulse — Confidential Executive Report',
    systemAuditNotice: 'Generated by Automotive Pulse Platform | Integrity Driven Solutions Inc. (IDS)'
  }
};

export default BRANDING_CONFIG;
