/**
 * Canonical Shared Report Shell Engine for IDS Pulse
 * Sourced directly from BRANDING_CONFIG
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import BRANDING_CONFIG from '../config/brandingConfig.js';

export class SharedReportShell {
  /**
   * Validates mandatory schema fields before generating a report.
   */
  static validateReportData(dataObject, requiredFields = []) {
    const missing = [];
    requiredFields.forEach(field => {
      const val = dataObject[field];
      if (val === undefined || val === null || val === '' || (Array.isArray(val) && val.length === 0)) {
        missing.push(field);
      }
    });
    return {
      isValid: missing.length === 0,
      missingFields: missing
    };
  }

  /**
   * Initializes a branded jsPDF document with standard headers & logo.
   */
  static createDocument(options = {}) {
    const {
      title = 'IDS Pulse Official Report',
      referenceNo = 'REF-2026-000',
      orientation = 'portrait',
      confidentialityLevel = 'CONFIDENTIAL',
      actorName = 'System Auditor'
    } = options;

    const doc = new jsPDF({
      orientation: orientation,
      unit: 'mm',
      format: 'letter'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const isLandscape = orientation === 'landscape';

    // 1. Full approved logo in header (top-left)
    doc.addImage(
      BRANDING_CONFIG.logo.canonical,
      'PNG',
      14,
      10,
      BRANDING_CONFIG.logo.defaultHeaderWidthMm,
      BRANDING_CONFIG.logo.defaultHeaderHeightMm
    );

    // 2. Organization & Product Title Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(BRANDING_CONFIG.typography.minHeadingSizePt);
    doc.setTextColor(...BRANDING_CONFIG.colors.primaryRgb);
    doc.text(title, 14, 28);

    // 3. Confidentiality Badge (top-right)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...BRANDING_CONFIG.colors.secondaryRgb);
    doc.text(confidentialityLevel, pageWidth - 14, 15, { align: 'right' });

    // 4. Header Separator Line
    doc.setDrawColor(...BRANDING_CONFIG.colors.primaryRgb);
    doc.setLineWidth(1.2);
    doc.line(14, 32, pageWidth - 14, 32);

    return {
      doc,
      pageWidth,
      isLandscape,
      startY: 36,
      actorName,
      referenceNo
    };
  }

  /**
   * Renders standardized headers, footers, and page numbers across all pages.
   */
  static applyStandardFooter(doc, options = {}) {
    const {
      actorName = 'System Auditor',
      referenceNo = 'REF-2026-000'
    } = options;

    const pageCount = doc.internal.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const footerY = pageHeight - 12;

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      
      // Footer Divider Line
      doc.setDrawColor(...BRANDING_CONFIG.colors.borderRgb);
      doc.setLineWidth(0.5);
      doc.line(14, footerY - 4, pageWidth - 14, footerY - 4);

      // Left Footer: System notice & Actor
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...BRANDING_CONFIG.colors.textSecondaryRgb);
      doc.text(`${BRANDING_CONFIG.footer.systemAuditNotice} | Ref: ${referenceNo} | Generated by ${actorName}`, 14, footerY);

      // Right Footer: Page Numbers & Confidentiality
      doc.text(`Page ${i} of ${pageCount} | ${BRANDING_CONFIG.footer.confidentialNotice}`, pageWidth - 14, footerY, { align: 'right' });
    }
  }

  /**
   * Helper to render AutoTable with zero text truncation & dynamic row height.
   */
  static renderTable(doc, startY, head, body, customColumnStyles = {}) {
    autoTable(doc, {
      startY: startY,
      margin: { left: 14, right: 14 },
      head: head,
      body: body,
      styles: {
        fontSize: BRANDING_CONFIG.typography.minTableDataSizePt,
        cellPadding: 3,
        overflow: 'linebreak',
        textColor: BRANDING_CONFIG.colors.textRgb
      },
      headStyles: {
        fillColor: BRANDING_CONFIG.colors.primaryRgb,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: BRANDING_CONFIG.typography.minTableHeaderSizePt
      },
      columnStyles: customColumnStyles,
      showHead: 'everyPage',
      rowPageBreak: 'avoid'
    });

    return doc.lastAutoTable.finalY + 8;
  }
}

export default SharedReportShell;
